# =============================================================================
# Watchtower
# =============================================================================
# FUNDING
# -----------------------------------------------------------------------------
# Funding information for the project.
#
# :Authors: Fabio Craig Wimmer Florey <fabioflorey@icloud.com>
# :Version: 0.0.1
# :License: MIT-0


github: FabioFlorey
custom: # Replace with up to 4 custom sponsorships URLs, e.g.: [URL1, URL2]
