# =============================================================================
# Watchtower
# =============================================================================
# Continuous Delivery
# -----------------------------------------------------------------------------
# Configuration file for GitHub Actions.
#
# :Authors: Fabio Craig Wimmer Florey <fabioflorey@icloud.com>
# :Version: 0.0.1
# :License: MIT-0


name: Continuous Delivery

on:
   workflow_run:
     workflows: ["Continuous Integration"]
     types: [completed] #requested

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Build package
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      run: |
        python -m pip install wheel
        python -m setup sdist bdist_wheel
    - name: Upload artifact
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      uses: actions/upload-artifact@v3
      with:
        name: built-package
        path: dist/*